version: '3.1'
services:
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 300 1 --loglevel warning
    volumes:
      - cache:/data

  db:
    restart: always
    image: postgres:alpine
    env_file:
      - ./src/.env
    ports:
      - 5432:5432

  hash:
    restart: always
    build:
      context: src/hash
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db

  app:
    restart: always
    build:
      context: src/app
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    ports:
      - 9000:80
    depends_on:
      - db
      - hash

volumes:
  cache:
